
# pubspec.yaml

name: kyokushuushi
description: "筋カウンターαアプリ"
publish_to: none
version: 1.0.0+1

environment:
  # Dart SDK は2.18以降、Flutter 3以降に対応
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI・機能系
  cupertino_icons:  ^1.0.5
  provider:         ^6.0.5
  google_fonts:     ^4.0.4
  animated_text_kit: ^4.2.2

  # オーディオ系
  audioplayers: ^6.4.0

  # Web対応が必要ならこちらも
  soundpool_web:     ^2.2.0

  # 設定・広告・課金
  shared_preferences: ^2.2.0
  google_mobile_ads:  ^3.0.0
  in_app_purchase:    ^3.1.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/   # フォルダ丸ごと指定
    - assets/images/chun.png

  fonts:
    - family: MPLUSRounded1c
      fonts:
        - asset: assets/fonts/MPLUSRounded1c-Regular.ttf
        - asset: assets/fonts/MPLUSRounded1c-Medium.ttf
          weight: 500
        - asset: assets/fonts/MPLUSRounded1c-Bold.ttf
          weight: 700
